name: interaction-complexity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pyyaml
  - pytest
  - pip
  - pip:
      - commonroad-io
      - commonroad-reach
      - commonroad-drivability-checker
